/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jnix.h>
/* Header for class org_opensc_pkcs11_wrap_PKCS11Session */

#ifndef _Included_org_opensc_pkcs11_wrap_PKCS11Session
#define _Included_org_opensc_pkcs11_wrap_PKCS11Session
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opensc_pkcs11_wrap_PKCS11Session_OPEN_MODE_READ_ONLY
#define org_opensc_pkcs11_wrap_PKCS11Session_OPEN_MODE_READ_ONLY 0L
#undef org_opensc_pkcs11_wrap_PKCS11Session_OPEN_MODE_READ_WRITE
#define org_opensc_pkcs11_wrap_PKCS11Session_OPEN_MODE_READ_WRITE 1L
/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Session
 * Method:    openNative
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_wrap_PKCS11Session_openNative)
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Session
 * Method:    closeNative
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_wrap_PKCS11Session_closeNative)
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Session
 * Method:    loginNative
 * Signature: (JJJI[B)V
 */
JNIEXPORT void JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_wrap_PKCS11Session_loginNative)
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jbyteArray);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Session
 * Method:    logoutNative
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL JNIX_FUNC_NAME(Java_org_opensc_pkcs11_wrap_PKCS11Session_logoutNative)
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
