/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensc_pkcs11_wrap_PKCS11Object */

#ifndef _Included_org_opensc_pkcs11_wrap_PKCS11Object
#define _Included_org_opensc_pkcs11_wrap_PKCS11Object
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opensc_pkcs11_wrap_PKCS11Object_CKO_CERTIFICATE
#define org_opensc_pkcs11_wrap_PKCS11Object_CKO_CERTIFICATE 1L
#undef org_opensc_pkcs11_wrap_PKCS11Object_CKO_PUBLIC_KEY
#define org_opensc_pkcs11_wrap_PKCS11Object_CKO_PUBLIC_KEY 2L
#undef org_opensc_pkcs11_wrap_PKCS11Object_CKO_PRIVATE_KEY
#define org_opensc_pkcs11_wrap_PKCS11Object_CKO_PRIVATE_KEY 3L
#undef org_opensc_pkcs11_wrap_PKCS11Object_CKO_SECRET_KEY
#define org_opensc_pkcs11_wrap_PKCS11Object_CKO_SECRET_KEY 4L
/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Object
 * Method:    enumObjectsNative
 * Signature: (JJJ[Lorg/opensc/pkcs11/wrap/PKCS11Attribute;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_opensc_pkcs11_wrap_PKCS11Object_enumObjectsNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jobjectArray);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Object
 * Method:    getAttributeNative
 * Signature: (JJJJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_opensc_pkcs11_wrap_PKCS11Object_getAttributeNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Object
 * Method:    getULongAttributeNative
 * Signature: (JJJJI)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_pkcs11_wrap_PKCS11Object_getULongAttributeNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Object
 * Method:    getBooleanAttributeNative
 * Signature: (JJJJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_opensc_pkcs11_wrap_PKCS11Object_getBooleanAttributeNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Object
 * Method:    getAllowedMechanismsNative
 * Signature: (JJJJ)[Lorg/opensc/pkcs11/wrap/PKCS11Mechanism;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensc_pkcs11_wrap_PKCS11Object_getAllowedMechanismsNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_opensc_pkcs11_wrap_PKCS11Object
 * Method:    createObjectNative
 * Signature: (JJJ[Lorg/opensc/pkcs11/wrap/PKCS11Attribute;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensc_pkcs11_wrap_PKCS11Object_createObjectNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
